version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/app
     - ../../manga:/app/image
    command: python webtoon_downloader.py "https://www.webtoons.com/en/romance/retired-demon-king/list?title_no=5111" --seperate  --images-format 'png' 


